# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05.receive_messasge.ipynb.

# %% auto 0
__all__ = ['receive_message']

# %% ../nbs/05.receive_messasge.ipynb 3
import subprocess
import os
import signal
import time
import sys
import io
# from multiprocessing import Process, Event
# from multiprocessing import synchronize, Manager
# from multiprocessing.managers import DictProxy
from typing import Optional
from datetime import datetime
import json

# %% ../nbs/05.receive_messasge.ipynb 4
import can
from can.interface import Bus
from can import Message 
import cantools
from cantools.database import Message as MessageTpl

# %% ../nbs/05.receive_messasge.ipynb 11
def receive_message(message_proxy: DictProxy,bus: Bus)->None:
	print('waiting for message')
	msg:Message = bus.recv()
	print('message received')
	message_proxy['timestamp'] = msg.timestamp
	message_proxy['arbitration_id'] = msg.arbitration_id
	message_proxy['data']=msg.data
